BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC_INDEX1';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC_INDEX2';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC_INDEX3';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE MAJESTIC (
 GlobalRank INT,
 TldRank INT,
 Domain VARCHAR(100),
 TLD VARCHAR(20),
 RefSubNets INT,
 RefIPs INT,
 IDN_Domain VARCHAR(100),
 IDN_TLD VARCHAR(20),
 PrevGlobalRank INT,
 PrevTldRank INT,
 PrevRefSubNets INT,
 PrevRefIPs INT);
 
CREATE TABLE MAJESTIC_INDEX1 (
 GlobalRank INT,
 TldRank INT,
 Domain VARCHAR(100),
 TLD VARCHAR(20),
 RefSubNets INT,
 RefIPs INT,
 IDN_Domain VARCHAR(100),
 IDN_TLD VARCHAR(20),
 PrevGlobalRank INT,
 PrevTldRank INT,
 PrevRefSubNets INT,
 PrevRefIPs INT);
 
CREATE INDEX ind_majestic_index1 ON MAJESTIC_INDEX1 (TLD);
 
CREATE TABLE MAJESTIC_INDEX2 (
 GlobalRank INT,
 TldRank INT,
 Domain VARCHAR(100),
 TLD VARCHAR(20),
 RefSubNets INT,
 RefIPs INT,
 IDN_Domain VARCHAR(100),
 IDN_TLD VARCHAR(20),
 PrevGlobalRank INT,
 PrevTldRank INT,
 PrevRefSubNets INT,
 PrevRefIPs INT);
 
CREATE INDEX ind_majestic_index2 ON MAJESTIC_INDEX2 (RefSubNets);

CREATE TABLE MAJESTIC_INDEX3 (
 GlobalRank INT,
 TldRank INT,
 Domain VARCHAR(100),
 TLD VARCHAR(20),
 RefSubNets INT,
 RefIPs INT,
 IDN_Domain VARCHAR(100),
 IDN_TLD VARCHAR(20),
 PrevGlobalRank INT,
 PrevTldRank INT,
 PrevRefSubNets INT,
 PrevRefIPs INT);

CREATE INDEX ind_majestic_index3 ON MAJESTIC_INDEX3 (TLD, RefIPs); 
