SET TIMING ON;

SELECT Domain
FROM MAJESTIC
WHERE RefSubNets>=100000;

SELECT Domain
FROM MAJESTIC_INDEX1
WHERE RefSubNets>=100000;

SELECT Domain
FROM MAJESTIC_INDEX2
WHERE RefSubNets>=100000;

SELECT Domain
FROM MAJESTIC_INDEX3
WHERE RefSubNets>=100000;

SET TIMING OFF;